services:
  main:
    image: main:dev
    container_name: main
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    depends_on:
      db:
        condition: service_healthy
      mq:
        condition: service_started
    volumes:
      - ./config:/app/config
      - ./internal/database/postgres/migrations:/app/internal/database/postgres/migrations

  db:
    container_name: db
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  mq:
    container_name: mq
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      
volumes:
  db_data: